### ISSUE TITLE
VM4862:6 Uncaught ReferenceError: addNewButton is not defined

### ISSUE THREAD

**Issue by luke-robertson** [mattheu/modular-page-builder#18]
Clean install of plugin

WP 4.5

problem occurs in admin page panel 
added a screen shot of problem

![screen shot 2016-04-18 at 13 51 58](https://cloud.githubusercontent.com/assets/11962756/14604674/bee7a7c6-056c-11e6-863b-f19764ede467.png)

**Comment by roborourke** [comment]
@prependto this is because underscore.js and backbone.js were updated, the above PR fixes so you can use that branch now. We'll need to tag the <= 4.4 compatible version before it can be merged I think.

In this case it's not straight forward and a fair bit of effort to provide a single version with back compat. Agree with that @mattheu @joehoyle?

**Comment by roborourke** [comment]
@prependto and thanks for logging the issue!

**Comment by joehoyle** [comment]
Yeah this is a compat issue I also ran into it yesterday, need to debug.

**Comment by joehoyle** [comment]
Oh this was fixed by https://github.com/humanmade/modular-page-builder/pull/25 ?

**Comment by roborourke** [comment]
Yarp 😁

## 

_Robert O'Rourke_
Senior WordPress Engineer
humanmade

_phone: *+447816329424
*email:_ rob@hmn.md
_skype:_ rob.o.rourke
_twitr:_ @sanchothefat https://twitter.com/sanchothefat
